apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "kohlisamdeep@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "edjn ppxv brpw kgsf"
type: Opaque

# Passw0rd@1234
